server:
  service_a_port: 50051
  service_b_port: 50052
  metrics_port: 9091

workers:
  max_python_workers: 10

paths:
  azure_path: "./Data/Azure"
  model_cache: "./Data/model_cache"
  kafka_install_dir: "C:/kafka_2.13-4.1.0"

drift:
  threshold: 0.1

connections:
  duckdb_path: "./Data/Offline_Store.duckdb"
  redis_addr: "redis:6379"
  azure_conn: "UseDevelopmentStorage=true"
  kafka_addr: "127.0.0.1:9092"
  kafka_topic: "TEST-TOPIC"

