version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis_store
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_monitor
    ports:
      - "9090:9090"
    volumes:
      - ./Prometheus.yml:/etc/prometheus/Prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ai_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_dashboard
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./Grafana_Datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - ai_network

volumes:
  redis_data:
  grafana_data:

networks:
  ai_network:
    driver: bridge

