apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  Prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'ai_infra_services'
        static_configs:
          - targets: ['ai-infra-app:9091']

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus:9090
        access: proxy
        isDefault: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  App.yaml: |
    server:
      service_a_port: 50051
      service_b_port: 50052
      metrics_port: 9091

    workers:
      max_python_workers: 10

    paths:
      azure_path: "./Data/Azure"
      model_cache: "./Data/model_cache"
      kafka_install_dir: "/tmp/kafka" # Not used in K8s mode, but path required

    drift:
      threshold: 0.1

    connections:
      duckdb_path: "./Data/Offline_Store.duckdb"
      redis_addr: "redis:6379"
      azure_conn: "UseDevelopmentStorage=true"
      kafka_addr: "kafka:9092"
      kafka_topic: "TEST-TOPIC"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-data

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus/prometheus.yml
          subPath: Prometheus.yml
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-config

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: LoadBalancer
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: prometheus

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
        volumeMounts:
        - name: grafana-data
          mountPath: /var/lib/grafana
        - name: datasources-volume
          mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
          subPath: datasources.yaml
      volumes:
      - name: grafana-data
        persistentVolumeClaim:
          claimName: grafana-data
      - name: datasources-volume
        configMap:
          name: grafana-datasources

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: grafana

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-infra-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-infra-app
  template:
    metadata:
      labels:
        app: ai-infra-app
    spec:
      imagePullSecrets:
      - name: ghcr-cred # this points to my k3 secret. it's used to pull the docker images
      containers:
      - name: ai-infra-app
        # Defined in Global_Configs/Image_Names.txt
        image: ghcr.io/sethmichel/ai-infra-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
          name: service-a
        - containerPort: 50052
          name: service-b
        - containerPort: 9091
          name: metrics
        env:
        - name: RUN_IN_K3S
          value: "true"
        - name: AZURE_STORAGE_CONNECTION_STRING
          value: "UseDevelopmentStorage=true"
        volumeMounts:
        - name: config-volume
          mountPath: /app/Global_Configs/App.yaml
          subPath: App.yaml
        - name: app-data
          mountPath: /app/Data
      volumes:
      - name: config-volume
        configMap:
          name: app-config
      - name: app-data
        persistentVolumeClaim:
          claimName: app-data

---
apiVersion: v1
kind: Service
metadata:
  name: ai-infra-app
spec:
  type: LoadBalancer
  ports:
  - port: 50051
    targetPort: 50051
    name: service-a
  - port: 50052
    targetPort: 50052
    name: service-b
  - port: 9091
    targetPort: 9091
    name: metrics
  selector:
    app: ai-infra-app
