// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: Proto/My_Service.proto

package myservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	FeatureName   string                 `protobuf:"bytes,2,opt,name=feature_name,json=featureName,proto3" json:"feature_name,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // ISO 8601 string for simplicity
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_Proto_My_Service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_My_Service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_Proto_My_Service_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Event) GetFeatureName() string {
	if x != nil {
		return x.FeatureName
	}
	return ""
}

func (x *Event) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Event) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// File Upload Messages
type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"` // Sent with the first chunk or every chunk (simple)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_Proto_My_Service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_My_Service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_Proto_My_Service_proto_rawDescGZIP(), []int{1}
}

func (x *FileChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileChunk) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type UploadStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadStatus) Reset() {
	*x = UploadStatus{}
	mi := &file_Proto_My_Service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadStatus) ProtoMessage() {}

func (x *UploadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_My_Service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadStatus.ProtoReflect.Descriptor instead.
func (*UploadStatus) Descriptor() ([]byte, []int) {
	return file_Proto_My_Service_proto_rawDescGZIP(), []int{2}
}

func (x *UploadStatus) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Prediction Messages
type PredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	FeatureNames  []string               `protobuf:"bytes,2,rep,name=feature_names,json=featureNames,proto3" json:"feature_names,omitempty"` // potentially override values or context
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_Proto_My_Service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_My_Service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_Proto_My_Service_proto_rawDescGZIP(), []int{3}
}

func (x *PredictRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *PredictRequest) GetFeatureNames() []string {
	if x != nil {
		return x.FeatureNames
	}
	return nil
}

type PredictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Prediction    float64                `protobuf:"fixed64,2,opt,name=prediction,proto3" json:"prediction,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_Proto_My_Service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_My_Service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_Proto_My_Service_proto_rawDescGZIP(), []int{4}
}

func (x *PredictResponse) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *PredictResponse) GetPrediction() float64 {
	if x != nil {
		return x.Prediction
	}
	return 0
}

func (x *PredictResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

// Internal Python Worker Messages
type TransformRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"` // Raw events to transform
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformRequest) Reset() {
	*x = TransformRequest{}
	mi := &file_Proto_My_Service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformRequest) ProtoMessage() {}

func (x *TransformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_My_Service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformRequest.ProtoReflect.Descriptor instead.
func (*TransformRequest) Descriptor() ([]byte, []int) {
	return file_Proto_My_Service_proto_rawDescGZIP(), []int{5}
}

func (x *TransformRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type TransformResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Features      []*Event               `protobuf:"bytes,1,rep,name=features,proto3" json:"features,omitempty"` // Transformed features
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformResponse) Reset() {
	*x = TransformResponse{}
	mi := &file_Proto_My_Service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformResponse) ProtoMessage() {}

func (x *TransformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_My_Service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformResponse.ProtoReflect.Descriptor instead.
func (*TransformResponse) Descriptor() ([]byte, []int) {
	return file_Proto_My_Service_proto_rawDescGZIP(), []int{6}
}

func (x *TransformResponse) GetFeatures() []*Event {
	if x != nil {
		return x.Features
	}
	return nil
}

type InferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Features      []*Event               `protobuf:"bytes,1,rep,name=features,proto3" json:"features,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferenceRequest) Reset() {
	*x = InferenceRequest{}
	mi := &file_Proto_My_Service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceRequest) ProtoMessage() {}

func (x *InferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_My_Service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceRequest.ProtoReflect.Descriptor instead.
func (*InferenceRequest) Descriptor() ([]byte, []int) {
	return file_Proto_My_Service_proto_rawDescGZIP(), []int{7}
}

func (x *InferenceRequest) GetFeatures() []*Event {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *InferenceRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

type InferenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prediction    float64                `protobuf:"fixed64,1,opt,name=prediction,proto3" json:"prediction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferenceResponse) Reset() {
	*x = InferenceResponse{}
	mi := &file_Proto_My_Service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceResponse) ProtoMessage() {}

func (x *InferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_My_Service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceResponse.ProtoReflect.Descriptor instead.
func (*InferenceResponse) Descriptor() ([]byte, []int) {
	return file_Proto_My_Service_proto_rawDescGZIP(), []int{8}
}

func (x *InferenceResponse) GetPrediction() float64 {
	if x != nil {
		return x.Prediction
	}
	return 0
}

type DriftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasetId     string                 `protobuf:"bytes,1,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"` // e.g., "training_v1" vs "serving_last_hour"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriftRequest) Reset() {
	*x = DriftRequest{}
	mi := &file_Proto_My_Service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriftRequest) ProtoMessage() {}

func (x *DriftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_My_Service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriftRequest.ProtoReflect.Descriptor instead.
func (*DriftRequest) Descriptor() ([]byte, []int) {
	return file_Proto_My_Service_proto_rawDescGZIP(), []int{9}
}

func (x *DriftRequest) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

type DriftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriftScore    float64                `protobuf:"fixed64,1,opt,name=drift_score,json=driftScore,proto3" json:"drift_score,omitempty"`
	DriftDetected bool                   `protobuf:"varint,2,opt,name=drift_detected,json=driftDetected,proto3" json:"drift_detected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriftResponse) Reset() {
	*x = DriftResponse{}
	mi := &file_Proto_My_Service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriftResponse) ProtoMessage() {}

func (x *DriftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_My_Service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriftResponse.ProtoReflect.Descriptor instead.
func (*DriftResponse) Descriptor() ([]byte, []int) {
	return file_Proto_My_Service_proto_rawDescGZIP(), []int{10}
}

func (x *DriftResponse) GetDriftScore() float64 {
	if x != nil {
		return x.DriftScore
	}
	return 0
}

func (x *DriftResponse) GetDriftDetected() bool {
	if x != nil {
		return x.DriftDetected
	}
	return false
}

type TrainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasetPath   string                 `protobuf:"bytes,1,opt,name=dataset_path,json=datasetPath,proto3" json:"dataset_path,omitempty"`
	ModelType     string                 `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainRequest) Reset() {
	*x = TrainRequest{}
	mi := &file_Proto_My_Service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainRequest) ProtoMessage() {}

func (x *TrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_My_Service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainRequest.ProtoReflect.Descriptor instead.
func (*TrainRequest) Descriptor() ([]byte, []int) {
	return file_Proto_My_Service_proto_rawDescGZIP(), []int{11}
}

func (x *TrainRequest) GetDatasetPath() string {
	if x != nil {
		return x.DatasetPath
	}
	return ""
}

func (x *TrainRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

type TrainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,3,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainResponse) Reset() {
	*x = TrainResponse{}
	mi := &file_Proto_My_Service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainResponse) ProtoMessage() {}

func (x *TrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_My_Service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainResponse.ProtoReflect.Descriptor instead.
func (*TrainResponse) Descriptor() ([]byte, []int) {
	return file_Proto_My_Service_proto_rawDescGZIP(), []int{12}
}

func (x *TrainResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TrainResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *TrainResponse) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

type TriggerJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobName       string                 `protobuf:"bytes,1,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerJobRequest) Reset() {
	*x = TriggerJobRequest{}
	mi := &file_Proto_My_Service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerJobRequest) ProtoMessage() {}

func (x *TriggerJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_My_Service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerJobRequest.ProtoReflect.Descriptor instead.
func (*TriggerJobRequest) Descriptor() ([]byte, []int) {
	return file_Proto_My_Service_proto_rawDescGZIP(), []int{13}
}

func (x *TriggerJobRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

type TriggerJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerJobResponse) Reset() {
	*x = TriggerJobResponse{}
	mi := &file_Proto_My_Service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerJobResponse) ProtoMessage() {}

func (x *TriggerJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_My_Service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerJobResponse.ProtoReflect.Descriptor instead.
func (*TriggerJobResponse) Descriptor() ([]byte, []int) {
	return file_Proto_My_Service_proto_rawDescGZIP(), []int{14}
}

func (x *TriggerJobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TriggerJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

var File_Proto_My_Service_proto protoreflect.FileDescriptor

const file_Proto_My_Service_proto_rawDesc = "" +
	"\n" +
	"\x16Proto/My_Service.proto\x12\tmyservice\"{\n" +
	"\x05Event\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12!\n" +
	"\ffeature_name\x18\x02 \x01(\tR\vfeatureName\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"A\n" +
	"\tFileChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\"B\n" +
	"\fUploadStatus\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"R\n" +
	"\x0ePredictRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12#\n" +
	"\rfeature_names\x18\x02 \x03(\tR\ffeatureNames\"s\n" +
	"\x0fPredictResponse\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x1e\n" +
	"\n" +
	"prediction\x18\x02 \x01(\x01R\n" +
	"prediction\x12#\n" +
	"\rmodel_version\x18\x03 \x01(\tR\fmodelVersion\"<\n" +
	"\x10TransformRequest\x12(\n" +
	"\x06events\x18\x01 \x03(\v2\x10.myservice.EventR\x06events\"A\n" +
	"\x11TransformResponse\x12,\n" +
	"\bfeatures\x18\x01 \x03(\v2\x10.myservice.EventR\bfeatures\"_\n" +
	"\x10InferenceRequest\x12,\n" +
	"\bfeatures\x18\x01 \x03(\v2\x10.myservice.EventR\bfeatures\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\"3\n" +
	"\x11InferenceResponse\x12\x1e\n" +
	"\n" +
	"prediction\x18\x01 \x01(\x01R\n" +
	"prediction\"-\n" +
	"\fDriftRequest\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x01 \x01(\tR\tdatasetId\"W\n" +
	"\rDriftResponse\x12\x1f\n" +
	"\vdrift_score\x18\x01 \x01(\x01R\n" +
	"driftScore\x12%\n" +
	"\x0edrift_detected\x18\x02 \x01(\bR\rdriftDetected\"P\n" +
	"\fTrainRequest\x12!\n" +
	"\fdataset_path\x18\x01 \x01(\tR\vdatasetPath\x12\x1d\n" +
	"\n" +
	"model_type\x18\x02 \x01(\tR\tmodelType\"`\n" +
	"\rTrainResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12\x1a\n" +
	"\baccuracy\x18\x03 \x01(\x01R\baccuracy\".\n" +
	"\x11TriggerJobRequest\x12\x19\n" +
	"\bjob_name\x18\x01 \x01(\tR\ajobName\"E\n" +
	"\x12TriggerJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId2M\n" +
	"\fFeatureStore\x12=\n" +
	"\n" +
	"UploadFile\x12\x14.myservice.FileChunk\x1a\x17.myservice.UploadStatus(\x012P\n" +
	"\fModelServing\x12@\n" +
	"\aPredict\x12\x19.myservice.PredictRequest\x1a\x1a.myservice.PredictResponse2Y\n" +
	"\fJobScheduler\x12I\n" +
	"\n" +
	"TriggerJob\x12\x1c.myservice.TriggerJobRequest\x1a\x1d.myservice.TriggerJobResponse2\xaf\x02\n" +
	"\fPythonWorker\x12N\n" +
	"\x11TransformFeatures\x12\x1b.myservice.TransformRequest\x1a\x1c.myservice.TransformResponse\x12I\n" +
	"\fRunInference\x12\x1b.myservice.InferenceRequest\x1a\x1c.myservice.InferenceResponse\x12C\n" +
	"\x0eCalculateDrift\x12\x17.myservice.DriftRequest\x1a\x18.myservice.DriftResponse\x12?\n" +
	"\n" +
	"TrainModel\x12\x17.myservice.TrainRequest\x1a\x18.myservice.TrainResponseB\x0eZ\f./;myserviceb\x06proto3"

var (
	file_Proto_My_Service_proto_rawDescOnce sync.Once
	file_Proto_My_Service_proto_rawDescData []byte
)

func file_Proto_My_Service_proto_rawDescGZIP() []byte {
	file_Proto_My_Service_proto_rawDescOnce.Do(func() {
		file_Proto_My_Service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Proto_My_Service_proto_rawDesc), len(file_Proto_My_Service_proto_rawDesc)))
	})
	return file_Proto_My_Service_proto_rawDescData
}

var file_Proto_My_Service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_Proto_My_Service_proto_goTypes = []any{
	(*Event)(nil),              // 0: myservice.Event
	(*FileChunk)(nil),          // 1: myservice.FileChunk
	(*UploadStatus)(nil),       // 2: myservice.UploadStatus
	(*PredictRequest)(nil),     // 3: myservice.PredictRequest
	(*PredictResponse)(nil),    // 4: myservice.PredictResponse
	(*TransformRequest)(nil),   // 5: myservice.TransformRequest
	(*TransformResponse)(nil),  // 6: myservice.TransformResponse
	(*InferenceRequest)(nil),   // 7: myservice.InferenceRequest
	(*InferenceResponse)(nil),  // 8: myservice.InferenceResponse
	(*DriftRequest)(nil),       // 9: myservice.DriftRequest
	(*DriftResponse)(nil),      // 10: myservice.DriftResponse
	(*TrainRequest)(nil),       // 11: myservice.TrainRequest
	(*TrainResponse)(nil),      // 12: myservice.TrainResponse
	(*TriggerJobRequest)(nil),  // 13: myservice.TriggerJobRequest
	(*TriggerJobResponse)(nil), // 14: myservice.TriggerJobResponse
}
var file_Proto_My_Service_proto_depIdxs = []int32{
	0,  // 0: myservice.TransformRequest.events:type_name -> myservice.Event
	0,  // 1: myservice.TransformResponse.features:type_name -> myservice.Event
	0,  // 2: myservice.InferenceRequest.features:type_name -> myservice.Event
	1,  // 3: myservice.FeatureStore.UploadFile:input_type -> myservice.FileChunk
	3,  // 4: myservice.ModelServing.Predict:input_type -> myservice.PredictRequest
	13, // 5: myservice.JobScheduler.TriggerJob:input_type -> myservice.TriggerJobRequest
	5,  // 6: myservice.PythonWorker.TransformFeatures:input_type -> myservice.TransformRequest
	7,  // 7: myservice.PythonWorker.RunInference:input_type -> myservice.InferenceRequest
	9,  // 8: myservice.PythonWorker.CalculateDrift:input_type -> myservice.DriftRequest
	11, // 9: myservice.PythonWorker.TrainModel:input_type -> myservice.TrainRequest
	2,  // 10: myservice.FeatureStore.UploadFile:output_type -> myservice.UploadStatus
	4,  // 11: myservice.ModelServing.Predict:output_type -> myservice.PredictResponse
	14, // 12: myservice.JobScheduler.TriggerJob:output_type -> myservice.TriggerJobResponse
	6,  // 13: myservice.PythonWorker.TransformFeatures:output_type -> myservice.TransformResponse
	8,  // 14: myservice.PythonWorker.RunInference:output_type -> myservice.InferenceResponse
	10, // 15: myservice.PythonWorker.CalculateDrift:output_type -> myservice.DriftResponse
	12, // 16: myservice.PythonWorker.TrainModel:output_type -> myservice.TrainResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_Proto_My_Service_proto_init() }
func file_Proto_My_Service_proto_init() {
	if File_Proto_My_Service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Proto_My_Service_proto_rawDesc), len(file_Proto_My_Service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_Proto_My_Service_proto_goTypes,
		DependencyIndexes: file_Proto_My_Service_proto_depIdxs,
		MessageInfos:      file_Proto_My_Service_proto_msgTypes,
	}.Build()
	File_Proto_My_Service_proto = out.File
	file_Proto_My_Service_proto_goTypes = nil
	file_Proto_My_Service_proto_depIdxs = nil
}
