// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: My_Service.proto

package myservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Generic event structure
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	FeatureName   string                 `protobuf:"bytes,2,opt,name=feature_name,json=featureName,proto3" json:"feature_name,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // ISO 8601 string for simplicity
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_My_Service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_My_Service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_My_Service_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Event) GetFeatureName() string {
	if x != nil {
		return x.FeatureName
	}
	return ""
}

func (x *Event) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Event) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// File upload messages
type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_My_Service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_My_Service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_My_Service_proto_rawDescGZIP(), []int{1}
}

func (x *FileChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileChunk) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type UploadStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadStatus) Reset() {
	*x = UploadStatus{}
	mi := &file_My_Service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadStatus) ProtoMessage() {}

func (x *UploadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_My_Service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadStatus.ProtoReflect.Descriptor instead.
func (*UploadStatus) Descriptor() ([]byte, []int) {
	return file_My_Service_proto_rawDescGZIP(), []int{2}
}

func (x *UploadStatus) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Service B: Model Serving messages
type PredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	FeatureNames  []string               `protobuf:"bytes,2,rep,name=feature_names,json=featureNames,proto3" json:"feature_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_My_Service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_My_Service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_My_Service_proto_rawDescGZIP(), []int{3}
}

func (x *PredictRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *PredictRequest) GetFeatureNames() []string {
	if x != nil {
		return x.FeatureNames
	}
	return nil
}

type PredictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Prediction    float64                `protobuf:"fixed64,2,opt,name=prediction,proto3" json:"prediction,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_My_Service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_My_Service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_My_Service_proto_rawDescGZIP(), []int{4}
}

func (x *PredictResponse) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *PredictResponse) GetPrediction() float64 {
	if x != nil {
		return x.Prediction
	}
	return 0
}

func (x *PredictResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

// Python Worker: Transform messages
type TransformRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformRequest) Reset() {
	*x = TransformRequest{}
	mi := &file_My_Service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformRequest) ProtoMessage() {}

func (x *TransformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_My_Service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformRequest.ProtoReflect.Descriptor instead.
func (*TransformRequest) Descriptor() ([]byte, []int) {
	return file_My_Service_proto_rawDescGZIP(), []int{5}
}

func (x *TransformRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type TransformResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Features      []*Event               `protobuf:"bytes,1,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformResponse) Reset() {
	*x = TransformResponse{}
	mi := &file_My_Service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformResponse) ProtoMessage() {}

func (x *TransformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_My_Service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformResponse.ProtoReflect.Descriptor instead.
func (*TransformResponse) Descriptor() ([]byte, []int) {
	return file_My_Service_proto_rawDescGZIP(), []int{6}
}

func (x *TransformResponse) GetFeatures() []*Event {
	if x != nil {
		return x.Features
	}
	return nil
}

// Python Worker: Inference messages
type InferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Features      map[string]string      `protobuf:"bytes,2,rep,name=features,proto3" json:"features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferenceRequest) Reset() {
	*x = InferenceRequest{}
	mi := &file_My_Service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceRequest) ProtoMessage() {}

func (x *InferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_My_Service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceRequest.ProtoReflect.Descriptor instead.
func (*InferenceRequest) Descriptor() ([]byte, []int) {
	return file_My_Service_proto_rawDescGZIP(), []int{7}
}

func (x *InferenceRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *InferenceRequest) GetFeatures() map[string]string {
	if x != nil {
		return x.Features
	}
	return nil
}

type InferenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prediction    float64                `protobuf:"fixed64,1,opt,name=prediction,proto3" json:"prediction,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferenceResponse) Reset() {
	*x = InferenceResponse{}
	mi := &file_My_Service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceResponse) ProtoMessage() {}

func (x *InferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_My_Service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceResponse.ProtoReflect.Descriptor instead.
func (*InferenceResponse) Descriptor() ([]byte, []int) {
	return file_My_Service_proto_rawDescGZIP(), []int{8}
}

func (x *InferenceResponse) GetPrediction() float64 {
	if x != nil {
		return x.Prediction
	}
	return 0
}

func (x *InferenceResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Python Worker: Drift messages
type DriftRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If empty, analyze all production models.
	// Can specify specific model_id if needed in future.
	ModelId       string `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriftRequest) Reset() {
	*x = DriftRequest{}
	mi := &file_My_Service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriftRequest) ProtoMessage() {}

func (x *DriftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_My_Service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriftRequest.ProtoReflect.Descriptor instead.
func (*DriftRequest) Descriptor() ([]byte, []int) {
	return file_My_Service_proto_rawDescGZIP(), []int{9}
}

func (x *DriftRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type FeatureDriftMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeatureName   string                 `protobuf:"bytes,1,opt,name=feature_name,json=featureName,proto3" json:"feature_name,omitempty"`
	KsStat        float64                `protobuf:"fixed64,2,opt,name=ks_stat,json=ksStat,proto3" json:"ks_stat,omitempty"`
	KsPValue      float64                `protobuf:"fixed64,3,opt,name=ks_p_value,json=ksPValue,proto3" json:"ks_p_value,omitempty"`
	Psi           float64                `protobuf:"fixed64,4,opt,name=psi,proto3" json:"psi,omitempty"`
	KlDivergence  float64                `protobuf:"fixed64,5,opt,name=kl_divergence,json=klDivergence,proto3" json:"kl_divergence,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // "PASS", "WARNING", "CRITICAL"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureDriftMetric) Reset() {
	*x = FeatureDriftMetric{}
	mi := &file_My_Service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureDriftMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureDriftMetric) ProtoMessage() {}

func (x *FeatureDriftMetric) ProtoReflect() protoreflect.Message {
	mi := &file_My_Service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureDriftMetric.ProtoReflect.Descriptor instead.
func (*FeatureDriftMetric) Descriptor() ([]byte, []int) {
	return file_My_Service_proto_rawDescGZIP(), []int{10}
}

func (x *FeatureDriftMetric) GetFeatureName() string {
	if x != nil {
		return x.FeatureName
	}
	return ""
}

func (x *FeatureDriftMetric) GetKsStat() float64 {
	if x != nil {
		return x.KsStat
	}
	return 0
}

func (x *FeatureDriftMetric) GetKsPValue() float64 {
	if x != nil {
		return x.KsPValue
	}
	return 0
}

func (x *FeatureDriftMetric) GetPsi() float64 {
	if x != nil {
		return x.Psi
	}
	return 0
}

func (x *FeatureDriftMetric) GetKlDivergence() float64 {
	if x != nil {
		return x.KlDivergence
	}
	return 0
}

func (x *FeatureDriftMetric) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ModelDriftResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ModelId        string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	DriftDetected  bool                   `protobuf:"varint,2,opt,name=drift_detected,json=driftDetected,proto3" json:"drift_detected,omitempty"`
	FeatureMetrics []*FeatureDriftMetric  `protobuf:"bytes,3,rep,name=feature_metrics,json=featureMetrics,proto3" json:"feature_metrics,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ModelDriftResult) Reset() {
	*x = ModelDriftResult{}
	mi := &file_My_Service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelDriftResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelDriftResult) ProtoMessage() {}

func (x *ModelDriftResult) ProtoReflect() protoreflect.Message {
	mi := &file_My_Service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelDriftResult.ProtoReflect.Descriptor instead.
func (*ModelDriftResult) Descriptor() ([]byte, []int) {
	return file_My_Service_proto_rawDescGZIP(), []int{11}
}

func (x *ModelDriftResult) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ModelDriftResult) GetDriftDetected() bool {
	if x != nil {
		return x.DriftDetected
	}
	return false
}

func (x *ModelDriftResult) GetFeatureMetrics() []*FeatureDriftMetric {
	if x != nil {
		return x.FeatureMetrics
	}
	return nil
}

type DriftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelResults  []*ModelDriftResult    `protobuf:"bytes,1,rep,name=model_results,json=modelResults,proto3" json:"model_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriftResponse) Reset() {
	*x = DriftResponse{}
	mi := &file_My_Service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriftResponse) ProtoMessage() {}

func (x *DriftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_My_Service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriftResponse.ProtoReflect.Descriptor instead.
func (*DriftResponse) Descriptor() ([]byte, []int) {
	return file_My_Service_proto_rawDescGZIP(), []int{12}
}

func (x *DriftResponse) GetModelResults() []*ModelDriftResult {
	if x != nil {
		return x.ModelResults
	}
	return nil
}

// Python Worker: Training messages
type TrainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasetPath   string                 `protobuf:"bytes,1,opt,name=dataset_path,json=datasetPath,proto3" json:"dataset_path,omitempty"`
	ModelType     string                 `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainRequest) Reset() {
	*x = TrainRequest{}
	mi := &file_My_Service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainRequest) ProtoMessage() {}

func (x *TrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_My_Service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainRequest.ProtoReflect.Descriptor instead.
func (*TrainRequest) Descriptor() ([]byte, []int) {
	return file_My_Service_proto_rawDescGZIP(), []int{13}
}

func (x *TrainRequest) GetDatasetPath() string {
	if x != nil {
		return x.DatasetPath
	}
	return ""
}

func (x *TrainRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

type TrainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,3,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainResponse) Reset() {
	*x = TrainResponse{}
	mi := &file_My_Service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainResponse) ProtoMessage() {}

func (x *TrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_My_Service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainResponse.ProtoReflect.Descriptor instead.
func (*TrainResponse) Descriptor() ([]byte, []int) {
	return file_My_Service_proto_rawDescGZIP(), []int{14}
}

func (x *TrainResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TrainResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *TrainResponse) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

// Service D: Job Scheduler messages
type TriggerJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobName       string                 `protobuf:"bytes,1,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerJobRequest) Reset() {
	*x = TriggerJobRequest{}
	mi := &file_My_Service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerJobRequest) ProtoMessage() {}

func (x *TriggerJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_My_Service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerJobRequest.ProtoReflect.Descriptor instead.
func (*TriggerJobRequest) Descriptor() ([]byte, []int) {
	return file_My_Service_proto_rawDescGZIP(), []int{15}
}

func (x *TriggerJobRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

type TriggerJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerJobResponse) Reset() {
	*x = TriggerJobResponse{}
	mi := &file_My_Service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerJobResponse) ProtoMessage() {}

func (x *TriggerJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_My_Service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerJobResponse.ProtoReflect.Descriptor instead.
func (*TriggerJobResponse) Descriptor() ([]byte, []int) {
	return file_My_Service_proto_rawDescGZIP(), []int{16}
}

func (x *TriggerJobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TriggerJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

var File_My_Service_proto protoreflect.FileDescriptor

const file_My_Service_proto_rawDesc = "" +
	"\n" +
	"\x10My_Service.proto\x12\tmyservice\"{\n" +
	"\x05Event\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12!\n" +
	"\ffeature_name\x18\x02 \x01(\tR\vfeatureName\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"A\n" +
	"\tFileChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\"B\n" +
	"\fUploadStatus\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"R\n" +
	"\x0ePredictRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12#\n" +
	"\rfeature_names\x18\x02 \x03(\tR\ffeatureNames\"s\n" +
	"\x0fPredictResponse\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x1e\n" +
	"\n" +
	"prediction\x18\x02 \x01(\x01R\n" +
	"prediction\x12#\n" +
	"\rmodel_version\x18\x03 \x01(\tR\fmodelVersion\"<\n" +
	"\x10TransformRequest\x12(\n" +
	"\x06events\x18\x01 \x03(\v2\x10.myservice.EventR\x06events\"A\n" +
	"\x11TransformResponse\x12,\n" +
	"\bfeatures\x18\x01 \x03(\v2\x10.myservice.EventR\bfeatures\"\xb5\x01\n" +
	"\x10InferenceRequest\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12E\n" +
	"\bfeatures\x18\x02 \x03(\v2).myservice.InferenceRequest.FeaturesEntryR\bfeatures\x1a;\n" +
	"\rFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"X\n" +
	"\x11InferenceResponse\x12\x1e\n" +
	"\n" +
	"prediction\x18\x01 \x01(\x01R\n" +
	"prediction\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\")\n" +
	"\fDriftRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\"\xbd\x01\n" +
	"\x12FeatureDriftMetric\x12!\n" +
	"\ffeature_name\x18\x01 \x01(\tR\vfeatureName\x12\x17\n" +
	"\aks_stat\x18\x02 \x01(\x01R\x06ksStat\x12\x1c\n" +
	"\n" +
	"ks_p_value\x18\x03 \x01(\x01R\bksPValue\x12\x10\n" +
	"\x03psi\x18\x04 \x01(\x01R\x03psi\x12#\n" +
	"\rkl_divergence\x18\x05 \x01(\x01R\fklDivergence\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\x9c\x01\n" +
	"\x10ModelDriftResult\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12%\n" +
	"\x0edrift_detected\x18\x02 \x01(\bR\rdriftDetected\x12F\n" +
	"\x0ffeature_metrics\x18\x03 \x03(\v2\x1d.myservice.FeatureDriftMetricR\x0efeatureMetrics\"Q\n" +
	"\rDriftResponse\x12@\n" +
	"\rmodel_results\x18\x01 \x03(\v2\x1b.myservice.ModelDriftResultR\fmodelResults\"P\n" +
	"\fTrainRequest\x12!\n" +
	"\fdataset_path\x18\x01 \x01(\tR\vdatasetPath\x12\x1d\n" +
	"\n" +
	"model_type\x18\x02 \x01(\tR\tmodelType\"`\n" +
	"\rTrainResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12\x1a\n" +
	"\baccuracy\x18\x03 \x01(\x01R\baccuracy\".\n" +
	"\x11TriggerJobRequest\x12\x19\n" +
	"\bjob_name\x18\x01 \x01(\tR\ajobName\"E\n" +
	"\x12TriggerJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId2M\n" +
	"\fFeatureStore\x12=\n" +
	"\n" +
	"UploadFile\x12\x14.myservice.FileChunk\x1a\x17.myservice.UploadStatus(\x012P\n" +
	"\fModelServing\x12@\n" +
	"\aPredict\x12\x19.myservice.PredictRequest\x1a\x1a.myservice.PredictResponse2Y\n" +
	"\fJobScheduler\x12I\n" +
	"\n" +
	"TriggerJob\x12\x1c.myservice.TriggerJobRequest\x1a\x1d.myservice.TriggerJobResponse2\xaf\x02\n" +
	"\fPythonWorker\x12N\n" +
	"\x11TransformFeatures\x12\x1b.myservice.TransformRequest\x1a\x1c.myservice.TransformResponse\x12I\n" +
	"\fRunInference\x12\x1b.myservice.InferenceRequest\x1a\x1c.myservice.InferenceResponse\x12C\n" +
	"\x0eCalculateDrift\x12\x17.myservice.DriftRequest\x1a\x18.myservice.DriftResponse\x12?\n" +
	"\n" +
	"TrainModel\x12\x17.myservice.TrainRequest\x1a\x18.myservice.TrainResponseB\x0eZ\f./;myserviceb\x06proto3"

var (
	file_My_Service_proto_rawDescOnce sync.Once
	file_My_Service_proto_rawDescData []byte
)

func file_My_Service_proto_rawDescGZIP() []byte {
	file_My_Service_proto_rawDescOnce.Do(func() {
		file_My_Service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_My_Service_proto_rawDesc), len(file_My_Service_proto_rawDesc)))
	})
	return file_My_Service_proto_rawDescData
}

var file_My_Service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_My_Service_proto_goTypes = []any{
	(*Event)(nil),              // 0: myservice.Event
	(*FileChunk)(nil),          // 1: myservice.FileChunk
	(*UploadStatus)(nil),       // 2: myservice.UploadStatus
	(*PredictRequest)(nil),     // 3: myservice.PredictRequest
	(*PredictResponse)(nil),    // 4: myservice.PredictResponse
	(*TransformRequest)(nil),   // 5: myservice.TransformRequest
	(*TransformResponse)(nil),  // 6: myservice.TransformResponse
	(*InferenceRequest)(nil),   // 7: myservice.InferenceRequest
	(*InferenceResponse)(nil),  // 8: myservice.InferenceResponse
	(*DriftRequest)(nil),       // 9: myservice.DriftRequest
	(*FeatureDriftMetric)(nil), // 10: myservice.FeatureDriftMetric
	(*ModelDriftResult)(nil),   // 11: myservice.ModelDriftResult
	(*DriftResponse)(nil),      // 12: myservice.DriftResponse
	(*TrainRequest)(nil),       // 13: myservice.TrainRequest
	(*TrainResponse)(nil),      // 14: myservice.TrainResponse
	(*TriggerJobRequest)(nil),  // 15: myservice.TriggerJobRequest
	(*TriggerJobResponse)(nil), // 16: myservice.TriggerJobResponse
	nil,                        // 17: myservice.InferenceRequest.FeaturesEntry
}
var file_My_Service_proto_depIdxs = []int32{
	0,  // 0: myservice.TransformRequest.events:type_name -> myservice.Event
	0,  // 1: myservice.TransformResponse.features:type_name -> myservice.Event
	17, // 2: myservice.InferenceRequest.features:type_name -> myservice.InferenceRequest.FeaturesEntry
	10, // 3: myservice.ModelDriftResult.feature_metrics:type_name -> myservice.FeatureDriftMetric
	11, // 4: myservice.DriftResponse.model_results:type_name -> myservice.ModelDriftResult
	1,  // 5: myservice.FeatureStore.UploadFile:input_type -> myservice.FileChunk
	3,  // 6: myservice.ModelServing.Predict:input_type -> myservice.PredictRequest
	15, // 7: myservice.JobScheduler.TriggerJob:input_type -> myservice.TriggerJobRequest
	5,  // 8: myservice.PythonWorker.TransformFeatures:input_type -> myservice.TransformRequest
	7,  // 9: myservice.PythonWorker.RunInference:input_type -> myservice.InferenceRequest
	9,  // 10: myservice.PythonWorker.CalculateDrift:input_type -> myservice.DriftRequest
	13, // 11: myservice.PythonWorker.TrainModel:input_type -> myservice.TrainRequest
	2,  // 12: myservice.FeatureStore.UploadFile:output_type -> myservice.UploadStatus
	4,  // 13: myservice.ModelServing.Predict:output_type -> myservice.PredictResponse
	16, // 14: myservice.JobScheduler.TriggerJob:output_type -> myservice.TriggerJobResponse
	6,  // 15: myservice.PythonWorker.TransformFeatures:output_type -> myservice.TransformResponse
	8,  // 16: myservice.PythonWorker.RunInference:output_type -> myservice.InferenceResponse
	12, // 17: myservice.PythonWorker.CalculateDrift:output_type -> myservice.DriftResponse
	14, // 18: myservice.PythonWorker.TrainModel:output_type -> myservice.TrainResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_My_Service_proto_init() }
func file_My_Service_proto_init() {
	if File_My_Service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_My_Service_proto_rawDesc), len(file_My_Service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_My_Service_proto_goTypes,
		DependencyIndexes: file_My_Service_proto_depIdxs,
		MessageInfos:      file_My_Service_proto_msgTypes,
	}.Build()
	File_My_Service_proto = out.File
	file_My_Service_proto_goTypes = nil
	file_My_Service_proto_depIdxs = nil
}
